version: "3.8"
services:
  postgres:
    image: postgres:16.1
    env_file:
      - .env
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_NAME
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
