// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/devmizumizurice/go-jwt-graphql/initializers"
	"github.com/devmizumizurice/go-jwt-graphql/repositories"
	"github.com/devmizumizurice/go-jwt-graphql/services"
)

// Injectors from wire.go:

func InitializeService() services.ServicesInterface {
	db := initializers.GetDB()
	userRepositoryInterface := repositories.NewUserRepository(db)
	authServiceInterface := services.NewAuthService(userRepositoryInterface)
	userServiceInterface := services.NewUserService(userRepositoryInterface)
	servicesInterface := services.NewServices(authServiceInterface, userServiceInterface)
	return servicesInterface
}
