// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gqlModels

type Mutation struct {
}

type Query struct {
}

type SignIn struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type SignUp struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type User struct {
	ID       string `json:"id"`
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Usr struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
